<?php

return [

    'base_path' => '/mnt/ssd1/cs2server/cs2-multiserver',

    'servers' => [
        [
            'name' => 'VersusCS #1',
            'instance' => 'lan01',
            'ip' => 'server.versuscs.hu',
            'port' => 27015,
            'ssh_user' => 'root',
            'config_path' => '/mnt/ssd1/msm.d/cs2/cfg/inst-lan01/server.conf',
            'whitelist_path' => '/mnt/ssd1/msm.d/cs2/cfg/inst-lan01/whitelist.txt',
            'log_path' => '/mnt/ssd1/msm.d/cs2/logs/lan01.log',
        ],
        [
            'name' => 'VersusCS #2',
            'instance' => 'lan02',
            'ip' => 'server.versuscs.hu',
            'port' => 27016,
            'ssh_user' => 'root',
            'config_path' => '/mnt/ssd1/msm.d/cs2/cfg/inst-lan02/server.conf',
            'whitelist_path' => '/mnt/ssd1/msm.d/cs2/cfg/inst-lan02/whitelist.txt',
            'log_path' => '/mnt/ssd1/msm.d/cs2/logs/lan02.log',
        ],
        [
            'name' => 'VersusCS #3',
            'instance' => 'lan03',
            'ip' => 'server.versuscs.hu',
            'port' => 27017,
            'ssh_user' => 'root',
            'config_path' => '/mnt/ssd1/msm.d/cs2/cfg/inst-lan03/server.conf',
            'whitelist_path' => '/mnt/ssd1/msm.d/cs2/cfg/inst-lan03/whitelist.txt',
            'log_path' => '/mnt/ssd1/msm.d/cs2/logs/lan03.log',
        ],
        [
            'name' => 'VersusCS #4',
            'instance' => 'lan04',
            'ip' => 'server.versuscs.hu',
            'port' => 27018,
            'ssh_user' => 'root',
            'config_path' => '/mnt/ssd1/msm.d/cs2/cfg/inst-lan04/server.conf',
            'whitelist_path' => '/mnt/ssd1/msm.d/cs2/cfg/inst-lan04/whitelist.txt',
            'log_path' => '/mnt/ssd1/msm.d/cs2/logs/lan04.log',
        ],
        [
            'name' => 'VersusCS #5',
            'instance' => 'lan05',
            'ip' => 'server.versuscs.hu',
            'port' => 27019,
            'ssh_user' => 'root',
            'config_path' => '/mnt/ssd1/msm.d/cs2/cfg/inst-lan05/server.conf',
            'whitelist_path' => '/mnt/ssd1/msm.d/cs2/cfg/inst-lan05/whitelist.txt',
            'log_path' => '/mnt/ssd1/msm.d/cs2/logs/lan05.log',
        ],
        [
            'name' => 'VersusCS #6',
            'instance' => 'lan06',
            'ip' => 'server.versuscs.hu',
            'port' => 27020,
            'ssh_user' => 'root',
            'config_path' => '/mnt/ssd1/msm.d/cs2/cfg/inst-lan06/server.conf',
            'whitelist_path' => '/mnt/ssd1/msm.d/cs2/cfg/inst-lan06/whitelist.txt',
            'log_path' => '/mnt/ssd1/msm.d/cs2/logs/lan06.log',
        ],
        [
            'name' => 'VersusCS #7',
            'instance' => 'lan07',
            'ip' => 'server.versuscs.hu',
            'port' => 27021,
            'ssh_user' => 'root',
            'config_path' => '/mnt/ssd1/msm.d/cs2/cfg/inst-lan07/server.conf',
            'whitelist_path' => '/mnt/ssd1/msm.d/cs2/cfg/inst-lan07/whitelist.txt',
            'log_path' => '/mnt/ssd1/msm.d/cs2/logs/lan07.log',
        ],
        [
            'name' => 'VersusCS #8',
            'instance' => 'lan08',
            'ip' => 'server.versuscs.hu',
            'port' => 27022,
            'ssh_user' => 'root',
            'config_path' => '/mnt/ssd1/msm.d/cs2/cfg/inst-lan08/server.conf',
            'whitelist_path' => '/mnt/ssd1/msm.d/cs2/cfg/inst-lan08/whitelist.txt',
            'log_path' => '/mnt/ssd1/msm.d/cs2/logs/lan08.log',
        ],
        [
            'name' => 'VersusCS #9',
            'instance' => 'lan09',
            'ip' => 'server.versuscs.hu',
            'port' => 27023,
            'ssh_user' => 'root',
            'config_path' => '/mnt/ssd1/msm.d/cs2/cfg/inst-lan09/server.conf',
            'whitelist_path' => '/mnt/ssd1/msm.d/cs2/cfg/inst-lan09/whitelist.txt',
            'log_path' => '/mnt/ssd1/msm.d/cs2/logs/lan09.log',
        ],
        [
            'name' => 'VersusCS #10',
            'instance' => 'lan10',
            'ip' => 'server.versuscs.hu',
            'port' => 27024,
            'ssh_user' => 'root',
            'config_path' => '/mnt/ssd1/msm.d/cs2/cfg/inst-lan10/server.conf',
            'whitelist_path' => '/mnt/ssd1/msm.d/cs2/cfg/inst-lan10/whitelist.txt',
            'log_path' => '/mnt/ssd1/msm.d/cs2/logs/lan10.log',
        ],
    ],
];
